spin_manifest_version = 2

[application]
name = "wasm_within_wasm"
version = "0.1.0"
description = "WASM all the way down"

[[trigger.http]]
route = "/..."
component = "wasm-within-wasm"

[component.wasm-within-wasm]
source = "target/wasm32-wasi/release/wasm_within_wasm.wasm"
allowed_outbound_hosts = []
[component.wasm-within-wasm.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/wasm/..."
component = "wasm"

[component.wasm]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "wasm/pkg", destination = "/pkg" }]
